### ISSUE TITLE
Add a mechanism for app updates

### ISSUE THREAD

**Issue by jimmywalsh** [pluralsight/git-collaborate#28]
I'm not sure how this is normally handled in electron. But it sucks that people will have to re-download the zip every time we do a release. I'm creating this issue so that we can start investigating what that would entail across platforms.

**Comment by jimboslicethat** [comment]
Apparently [this is a thing](https://electronjs.org/docs/api/auto-updater). But it will only work for windows & mac.

**Comment by jimboslicethat** [comment]
This isn't going to work well for the linux story. But I haven't been able to find a great alternative yet.

https://github.com/electron/electron/blob/master/docs/tutorial/updates.md

**Comment by parkerholladay** [comment]
I think that is fine. Worst case scenario, I can create a bash script that downloads a given version and updates git-switch for us linuxers. :penguin:

**Comment by jimboslicethat** [comment]
This just in after diving into the docs a bit this afternoon.: `Note: Your application must be signed for automatic updates on macOS. This is a requirement of Squirrel.Mac`. So looks like `autoUpdater` would really only benefit windows users as of today. Guess we need to address our CI before we address CD.

**Comment by jimboslicethat** [comment]
That being said. I did notice that this workflow depends on the `package.json` version being up to date. How would you feel about us adding `semantic-release` with `comittizen`?

**Comment by parkerholladay** [comment]
This isn't fully addressed, but the app can now check for latest version with #52
